<?php
// $Id: user_relationship_migrate.install,v 1.3 2007-10-24 06:30:08 jbchristy Exp $
  
/**
 * Implementation of hook_uninstall().
 */
function user_relationship_migrate_uninstall() {
  variable_del('user_relationship_migrate_checkpoint');
  variable_del('user_relationship_migrate_email');
  variable_del('user_relationship_migrate_pending');
  variable_del('user_relationship_migrate_rtype');
  variable_del('user_relationship_migrate_status');
}
