<?php
// $Id: user_relationship_migrate.install,v 1.2 2007-10-09 18:01:36 jbchristy Exp $
  
/**
 * Implementation of hook_uninstall().
 */
function user_relationship_migrate_uninstall() {
  variable_del('user_relationship_migrate_checkpoint');
  variable_del('user_relationship_migrate_pending');
  variable_del('user_relationship_migrate_rtype');
  variable_del('user_relationship_migrate_status');
}
