<?php
// $Id: user_relationship_elaborations.module,v 1.1.2.1 2008-03-02 11:46:12 sprsquish Exp $

/**
 *  User Relationships Elaborations
 */

/**
 * Save an elaboration to the DB
 *
 * @param $rid
 *    an integer, the relationship ID
 * @param $elaboration
 *    a string version of the elaboration. if you're only using the API side of this
 *    you could easily serialize the data 
 *
 * @return 
 *    An elaboration object or FALSE if the save was not successful
 */
function user_relationships_save_elaboration($rid, &$elaboration) {
  $record = array(
    'rid'         => $rid,
    'elaboration' => $elaboration,
  );

  return drupal_write_record('user_relationship_elaborations', $record);
}

/**
 * hook_user_relationships()
 */
function user_relationship_elaborations_user_relationships($op, &$relationships) {
  if (!is_array($relationships)) {
    $relationships->elaboration = db_result(db_query('SELECT elaboration FROM {user_relationship_elaborations} WHERE rid = %d'), $relationships->rid);

    if (in_array($op, array('cancel', 'delete', 'remove'))) {
      db_query('DELETE FROM {user_relationship_elaborations} WHERE rid = %d', $relationships->rid);
    }
  }
  else {
    $rids = array();
    _user_relationship_elaborations_walk_recursive('find_rids', $relationships, $rids);

    if ($rids) {
      $results = db_query('SELECT rid, elaboration FROM {user_relationship_elaborations} WHERE rid IN ('.db_placeholders($rids).')', $rids);
      while ($result = db_fetch_object($results)) {
        $elaborations[$result->rid] = $result->elaboration;
      }

      _user_relationship_elaborations_walk_recursive('load', $relationships, $elaborations);
    }
  }
}


/**
 * array_walk_recursive doesn't pass extra data by reference (lame!) so
 * we have to take care of it ourselves
 */
function _user_relationship_elaborations_walk_recursive($action, &$relationships, &$data) {
  foreach ($relationships as $relationship) {
    if (is_array($relationship)) {
      _user_relationship_elaborations_walk_recursive($action, $relationship, $data);
    }
    else {
      if ($action == 'find_rids') {
        $data[$relationship->rid] = $relationship->rid;
      }
      else {
        $relationship->elaboration = $data[$relationship->rid];
      }
    }
  }
}


/**
 * Add elaborations to relationships page through MODULE_preprocess_HOOK
 */
function user_relationship_elaborations_preprocess_user_relationships(&$variables) {
  if (!variable_get('user_relationships_elaborations_api_only', FALSE)) {
    user_relationship_elaborations_user_relationships('load', $variables['relationships']);
    foreach ($variables['relationships'] as $rid => $relationship) {
      $variables['relationships'][$rid]->extra_for_display .= $variables['relationships'][$rid]->elaboration;
    }
  }
}


/**
 * hook_form_alter() to catch the approval form
 */
function user_relationship_elaborations_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_relationships_ui_pending_requested' && $form['action']['#value'] == 'approve' && !variable_get('user_relationships_elaborations_api_only', FALSE)) {
    $form['elaboration'] = array(
      '#type'           => 'textarea',
      '#title'          => t('Elaboration'),
      '#default_value'  => $form_state['post']['elaboration'],
      '#description'    => t('Please elaborate on this relationship (how/where you met, etc)')
    );
    $form['#submit'][] = 'user_relationship_elaborations_submit';
  }
  else if ($form_id == 'user_relationships_ui_settings') {
    $form['user_relationships_elaborations'] = array(
      '#type'   => 'fieldset',
      '#title'  => t('Elaborations'),
      '#weight' => 0,
    );
      $form['user_relationships_elaborations']['user_relationships_elaborations_api_only'] = array(
        '#type'           => 'checkbox',
        '#title'          => t('Do not use the elaborations UI'),
        '#description'    => t('Check this if you only need the API provided by the UR-Elaborations module'),
        '#default_value'  => variable_get('user_relationships_elaborations_api_only', FALSE),
      );
  }
}


/**
 * process the submitted form and save the new record
 */
function user_relationship_elaborations_submit($form, &$form_state) {
  user_relationships_save_elaboration($form_state['values']['rid'], $form_state['values']['elaboration']);
}