<?php
// $Id: user_relationship_mailer.install,v 1.1.2.2 2008-03-02 11:46:13 sprsquish Exp $

function user_relationship_mailer_uninstall() {
  variable_del('user_relationship_mailer_send_mail');

  foreach ($user_relationship_mailer_ops as $op) {
    variable_del("user_relationship_mailer_send_{$op}");
    variable_del("user_relationships_mailer_{$op}_subject");
    variable_del("user_relationship_mailer_{$op}_message");
  }
}
