<?php
// $Id: user_relationship_mailer.module,v 1.1.2.3 2008-03-10 17:13:32 sprsquish Exp $

require_once(drupal_get_path('module', 'user_relationship_mailer').'/user_relationship_mailer_defaults.inc');

/**
 * Sends mail to the appropriate user
 *
 * @param $op
 *    string of action to take [request|delete|cancel|approve|disapprove|remove]
 *
 * @param $relationship
 *    object of the relationship
 *
 */
function user_relationship_mailer_send_email($op, $relationship) {
  if (($op == 'request' && $relationship->approved) || !variable_get("user_relationship_mailer_send_{$op}", TRUE)) { 
    return; 
  }

  $relationship->requester = $requester = user_load($relationship->requester_id);
  $relationship->requestee = $requestee = user_load($relationship->requestee_id);

  $send_to_requestee = isset($requestee->user_relationship_mailer_send_mail) ? $requestee->user_relationship_mailer_send_mail : TRUE;
  $send_to_requester = isset($requester->user_relationship_mailer_send_mail) ? $requester->user_relationship_mailer_send_mail : TRUE;

  $send_to = array();
  switch ($op) {
  case 'request':
  case 'cancel':
    $send_email = $send_to_requestee;
    $send_to[] = 'requestee';
    break;

  case 'approve':
  case 'disapprove':
    $send_email = $send_to_requester;
    $send_to[] = 'requester';
    break;

  case 'remove':
    $send_email = $send_to_requestee && $send_to_requester;
    $send_to[] = 'requester';
    if (!$relationship->is_oneway) {
      $send_to[] = 'requestee';
    }
    break;

  default:
    return;
  }

  if (variable_get('user_relationship_mailer_send_mail', FALSE) ? $send_email : variable_get("user_relationship_mailer_send_{$op}", TRUE)) {

    $relationship = user_relationships_load($relationship->rid);
    $relationship->requester = $requester;
    $relationship->requestee = $requestee;
    $replacements = user_relationship_mailer_replacements($relationship);

    foreach ($send_to as $target) {
      $target = $$target;
      if ($op == 'remove') {
        $replacements['@profile_uid'] = $target->uid;
      }

      drupal_mail(
        'user_relationship_mailer', 
        $op, 
        $target->mail, 
        user_preferred_language($target),
        $replacements
      );
    }
  }
}


/**
 * hook_mail()
 */
function user_relationship_mailer_mail($op, &$message, $replacements) {
  $defaults_function = "user_relationship_mailer_{$op}_default";
  $defaults = $defaults_function();

  $message['subject'] = t(variable_get("user_relationship_mailer_{$op}_subject", $defaults['subject']), $replacements);
  $message['body']    = t(variable_get("user_relationship_mailer_{$op}_message", $defaults['message']), $replacements);
}


/**
 * hook_user_relationships()
 */
function user_relationship_mailer_user_relationships($type, &$relationship, $category = NULL) {
  switch ($type) {
  case 'post-save':
  case 'delete':
    user_relationship_mailer_send_email($category, $relationship);
    break;
  }
}

/**
 * hook_form_alter()
 */
function user_relationship_mailer_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
  case 'user_relationships_ui_settings':
    global $user;
    $relationship = user_relationships_types_load();
    $relationship = array_pop($relationship);

    $form['mail'] = array(
      '#type'   => 'fieldset',
      '#title'  => t('Email Options'),
      '#weight' => -9,
    );
      $form['mail']['user_relationship_mailer_send_mail'] = array(
        '#type'           => 'checkbox',
        '#title'          => t('Allow users to turn off relationship messages'),
        '#default_value'  => variable_get('user_relationship_mailer_send_mail', FALSE),
        '#description'    => t('If you check this, users will have a new setting on their account edit page.'),
      );

      global $user_relationship_mailer_ops;
      foreach ($user_relationship_mailer_ops as $op) {
        $defaults_function = "user_relationship_mailer_{$op}_default";
        $defaults = $defaults_function();

        $form['mail'][$op] = array(
          '#type'         => 'fieldset',
          '#title'        => t(ucfirst($op)),
          '#collapsible'  => TRUE,
          '#collapsed'    => TRUE
        );
          $form['mail'][$op]["user_relationship_mailer_send_{$op}"] = array(
            '#type'           => 'checkbox',
            '#title'          => t('Send @op messages', array('@op' => $op)),
            '#default_value'  => variable_get("user_relationship_mailer_send_{$op}", TRUE),
          );
          $form['mail'][$op]["user_relationship_mailer_{$op}_subject"] = array(
            '#type'           => 'textfield',
            '#title'          => t('@Op relationship email subject', array('@Op' => ucfirst($op))),
            '#default_value'  => variable_get("user_relationship_mailer_{$op}_subject", $defaults['subject']),
          );
          $form['mail'][$op]["user_relationship_mailer_{$op}_message"] = array(
            '#type'           => 'textarea',
            '#title'          => t('@Op relationship email message', array('@Op' => ucfirst($op))),
            '#default_value'  => variable_get("user_relationship_mailer_{$op}_message", $defaults['message']),
            '#description'    => t('Replacement strings are: %macros', array('%macros' => implode(', ', array_keys(user_relationship_mailer_replacements($relationship))))),
          );
      }
    break;
  }
}

/**
 * hook_user()
 */
function user_relationship_mailer_user($type, &$edit, &$account, $category = NULL) {
  switch($type) {
  case 'form':
    $form = array();
    if (($category == 'account') 
      && variable_get('user_relationship_mailer_send_mail', FALSE)
      && user_access('maintain own relationships', $account)
    ) {
      $form['user_relationship_mailer_settings'] = array(
        '#type'   => 'fieldset',
        '#title'  => t('Relationship email settings'),
        '#weight' => 5
      );
        $form['user_relationship_mailer_settings']['user_relationship_mailer_send_mail'] = array(
          '#type'           => 'checkbox',
          '#title'          => t('Receive relationship email notifications'),
          '#options'        => $options,
          '#default_value'  => isset($edit['user_relationship_mailer_send_mail']) ? $edit['user_relationship_mailer_send_mail'] : TRUE,
          '#description'    => t("Check this if you'd like to receive relationship related email notifications")
        );
    }
    return $form;
  }  
}
